- package.json
- sandbox/example-ui/public/_redirects
Having a way to share previews seems like a good idea at this point. this sets it up so arranger.netlify.com points to the example ui and arranger.netlify.com/storybook will go to the components storybook.
> netlify command and config

- modules/components/src/DataTable/TableToolbar/saveTSV.js
streamsaver includes ES6 
project using arranger will need run it (ang graphql-fields) through babel.
example using create react app would be to use `react-app-rewired` and a config-override.js file containing something like 
```js
const path = require('path');
const fs = require('fs');
const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = relativePath => path.resolve(appDirectory, relativePath);
module.exports = function(config, env) {
config.module.rules[1].oneOf[1].include = [
config.module.rules[1].oneOf[1].include,
resolveApp('node_modules/graphql-fields'),
resolveApp('node_modules/streamsaver'),
];
return config;
};
```
> ✨enable streamsaver

- modules/middleware/package.json
- modules/middleware/src/aggregations.js
- modules/middleware/test/aggregations.test.js
original python code: https://github.com/NCI-GDC/gdcapi/blob/develop/gdcapi/graphql_schemas/utils.py#L898
In `build_aggregations`, the loop over `fields` is overriding the the entire collection of the nested fields on every iteration, resulting in the output `agg` being incorrect. This explains why only the last field of those that share common paths are resolved. This is likely because of the use of `Object.assign` which doesn't do a deep merge. There may be a difference in behaviour between python's library `update` method and the JS `Object.assign`, or there was some error in porting.
Particularly worth noting is that the call to `ensure_path_to_agg` is overriding `agg`. From comparing the code, this seems consistent with the original python code, but could use confirmation.
Some …
> 🐛 aggregations middleware bug

- modules/schema/src/Root.js
fixes graphql breaking with invalid graphql field name (sort of) should probably do proper validation on the dashboard
> 🐛 use type.name instead of index name for graphql field name

- modules/components/src/SQONView/index.js
- modules/components/src/SQONView/utils.js
- modules/components/src/TextFilter/TextFilter.js
- modules/middleware/src/aggregations.js
- modules/middleware/test/global_aggs.test.js
a little fix to enable range aggs to not filter themselves, similar to term aggs
> 🐛 range aggs should not filter themselves (like terms)

- modules/components/public/themeStyles/beagle/beagle.css
Current:
Without border on `-toEnd`
> Fixes extra border on last pagination button

- modules/mapping-utils/src/index.js
- modules/mapping-utils/src/mappingToFields.js
- modules/mapping-utils/src/mappingToNestedTypes.js
- modules/mapping-utils/src/mappingToObjectTypes.js
- modules/mapping-utils/src/mappingToScalarFields.js
- modules/mapping-utils/src/resolveHits.js
- modules/schema/src/Root.js
Array fields were coming back as `[object Object]` even if they were marked as `isArray`
> 🐛 fix handling of the  field in the extended mapping

- modules/components/src/Aggs/RangeAgg.js
- modules/components/src/Arranger/CurrentSQON.js
a few things here:
- a slightly more robust null check for the range agg, so it doesn't try to render the slider if it doesn't have the appropriate data to do so
- separated the current sqon extended mapping api fetching / state from the current sqon view component
- removed a react warning due to passing `nextSQON` prop through to a DOM element
> 🐛 a couple fixes from the capsid perspective

- modules/components/src/Aggs/TermAgg.js
Another capsid related item - capsid's agg bucket counts returned by search aren't accurate (due to its data model), and it's not feasible to give accurate counts within the time constraints of running a search. So, we're going to omit the counts and provide a button to fetch them if the user chooses.
Given the situation we need the term agg to render properly even if bucket count isn't present.
> 🐛 term agg - don't fall over if the bucket doesn't have a count

- modules/components/src/Aggs/RangeAgg.js
- modules/components/src/utils/mapObjectValues.js
Apparently the input range slider component we're using only handles integers, not doubles. In an effort to not swap out / rebuild the component altogether I'd like to suggest we add the ability to normalize / denormalize the numbers we give to & get from the range agg. Ex. normalize percentages to be between 0 & 100, rather than 0 & 1 (`normalize={x => x * 100}`, `denormalize={x => x / 100}`)
Also I've enabled the 'draggableTrack' prop, which lets you drag the previously selected range around. Ex. select 5->10, drag range to 4->9, 3->8, etc...
> 🐛 normalize / denormalize data in / out of range agg

- modules/mapping-utils/src/mappingToColumnsType.js
jsonPath handles double nested fields, so this filter can be removed.
> ✨ enable double nested colum configs

- modules/components/public/themeStyles/beagle/beagle.css
- modules/components/src/Aggs/AggregationCard.css
- modules/components/src/Aggs/AggsWrapper.js
- modules/components/src/Aggs/TermAgg.js
- modules/components/src/ToggleButton/ToggleButton.css
- modules/components/src/ToggleButton/ToggleButton.js
- modules/components/src/ToggleButton/index.js
Capsid needed the option to have a term aggregation that generates a 'not-in' term query, rather than an 'in' one. As a result I've added an include / exclude button to the TermAgg, split in the following ways:
- A 'ToggleButton' component
- The AggWrapper now accepts 'filters', to sit above the content of the agg
- TermAgg now accepts 'isExclude', 'showExcludeOption', and 'handleIncludeExcludeChange' as props
> ✨ term agg now has an include / exclude button option

- modules/middleware/src/buildQuery/index.js
- modules/middleware/src/buildQuery/normalizeFilters.js
right now you can add a `*` to any value in a `in` or `not-in` filter which is replaced with a `.*` regular expression. 
this changes it so you have to explicitly say the filter is a regular expression and will allow all regular expression features.
before:
```
{
op: 'in',
content: {
field: 'field',
value: ['bbb', 'aaa*']
}
}
```
after:
```
{
op: 'or',
content: [
{
op: 'in',
content: {
isRegex: true,
field: 'field',
value: ['aaa.*']
}
},
{
op: 'in',
content: {
field: 'field',
value: ['bbb']
}
}
]
}
```
> ✨ support all regex

- docker-compose.yml
run `docker-compose up` from root to spin up ES / kibana automatically, instead of manually installing / running locally
> ✨ docker compose for quick ES / kibana dev env

- modules/mapping-utils/package-lock.json
- modules/mapping-utils/src/createConnectionResolvers.js
- modules/mapping-utils/src/createConnectionTypeDefs.js
- modules/mapping-utils/src/mappingToFields.js
- modules/mapping-utils/src/mappingToNestedTypes.js
- modules/mapping-utils/src/mappingToObjectTypes.js
- modules/mapping-utils/src/resolveHits.js
- modules/mapping-utils/src/resolveSets.js
- modules/schema/package-lock.json
- modules/schema/src/Root.js
- modules/schema/src/index.js
- modules/server/src/startProject.js
- package-lock.json
Instead of custom sets resolver, concat sets into types array being passed to `generateTypeDefs` and `generateResolvers`. Works but let me know if it's a terrible idea.
> :sparkles: resolve sets

- modules/mapping-utils/src/mappingToNestedTypes.js
everywhere else `type` is an obj, but in `mappingToNestedTypes` it's a string. Sets will never have nested fields, and everywhere else the states are wanted, so I guess let `createState` default to true in `mappingToNestedTypes`
> :bug: default to createState true in mappingToNestedTypes

- modules/mapping-utils/src/createConnectionTypeDefs.js
- modules/mapping-utils/src/resolveAggregations.js
- modules/middleware/src/flattenAggregations.js
- modules/middleware/test/flattenAggregations.test.js
some app logic relies on the number of buckets, so giving the client the ability to specify whether or not to include the missing term in aggregations is helpful
> ✨ give the client the ability to include / exclude missing term

- modules/schema/src/index.js
change to using export default, used named export for sets mapping and silently didn't work with `module.exports`, making the terms filter for sets not work.
> :bug: fix sets mapping export

- modules/components/src/Aggs/TermAgg.js
- modules/components/src/Arranger/CurrentSQON.js
- modules/components/src/Arranger/QuickSearch/QuickSearch.js
- modules/components/src/utils/translateSQONValue.js
- modules/mapping-utils/src/resolveAggregations.js
- modules/middleware/src/buildAggregations.js
- modules/middleware/src/buildQuery/index.js
- modules/middleware/src/buildQuery/normalizeFilters.js
- modules/middleware/src/constants.js
- modules/middleware/src/flattenAggregations.js
- modules/middleware/test/buildQuery/buildQuery.test.js
- modules/middleware/test/buildQuery/buildQueryNested.test.js
- modules/middleware/test/flattenAggregations.test.js
a few things here:
1) rather than missing being its own operation, it's now a 'special' term in an `in` operation, the special term being `__missing__`
2) added a case so it won't filter itself in aggs
3) added a function to translate `__missing__` to `Missing` in the UI
> 🐛 parse / display the missing term in a term agg properly

- modules/components/src/DataTable/ColumnsState.js
- modules/components/src/DataTable/DataTable.js
- modules/components/src/DataTable/Table/Table.js
- modules/components/src/utils/saveSet.js
- modules/mapping-utils/src/resolveHits.js
- modules/mapping-utils/src/resolveSets.js
- modules/schema/src/Root.js
Figured out why sets of size >1000 would not create for HCMI data:
1) there's no id field in the hcmi data source, so `path: "id"` fails on `get(x, '_source.${path.split('__').join('.')}')`, so default to `_id`
2) if `path: name` and sort: [`_id`], `search_after` doesnt work properly, it keeps returning pages of 1000 and never reaches the end resulting in an infinite loop. Allow `sort` to be passed in.
> saveSet: allow specify sort and default id field to _id

- modules/components/src/Arranger/Table.js
- modules/components/src/DataTable/ColumnsState.js
- modules/components/src/DataTable/DataTable.js
- modules/components/src/DataTable/Table/Table.js
- prevent DataTable rendering when ColumnState is not loaded so that
fetch with no config does not occur overriding initialSelectedTableRows
> DataTable: allow pass in initialSelectedTableRows

- modules/components/package-lock.json
- modules/components/src/Admin/Tabs/Aggregations/TableTab.js
- modules/components/src/Aggs/AggsWrapper.js
- modules/components/src/Aggs/TermAgg.js
- modules/components/src/Arranger/Aggregations.js
- modules/components/src/DataTable/ColumnsState.js
2 things here:
- changes to columnstate broke some stuff in KF / arranger admin, so put in some safety checks for that
- when clicking 'less' on the term agg they want the term agg to stay in agg view (in a 'scrolling' aggregation sidebar context)
> 🐛 keep term agg in view on collapse

- modules/components/src/AdvancedFacetView/FacetView.js
- modules/components/src/Aggs/RangeAgg.js
- modules/components/src/Aggs/TermAgg.js
- modules/components/src/Aggs/aggComponentsMap.js
- modules/components/src/utils/translateSQONValue.js
3 changes:
- term agg to show 5 terms by default
- missing bucket to show up last in terms list
- missing bucket to display as 'No Data', rather than 'Missing'
> 💄 various requested changes

- modules/components/public/themeStyles/beagle/beagle.css
- modules/components/src/Aggs/RangeAgg.css
- modules/components/src/Aggs/RangeAgg.js
Changes:
- range agg stats were behind one prop cycle
- field from state 'cause why was it there in the first place
- locked range agg values to four corners around the slider, because values kept overlapping / colliding
- fixed boolean agg bucket count CSS
> 🐛 range agg fixes

- modules/components/src/AdvancedFacetView/utils.js
__missing__ doesn't count as a value
> 🐛 fix afv filter fields w/ no data

- modules/components/src/Aggs/BooleanAgg.js
- modules/components/src/Aggs/DatesAgg.js
- modules/components/src/Aggs/RangeAgg.js
- modules/components/src/Aggs/TermAgg.js
- modules/components/src/Aggs/aggComponentsMap.js
- modules/components/src/Arranger/Aggregations.js
When a user interacts with a facet/aggregation value propagate that call and it's value up to the highest parent component to allow for hooks into these events
> Propagate the selected facet/agg value up to the highest parent component

- modules/server/src/projects/index.js
- modules/server/src/projects/spinUp.js
- modules/server/src/server.js
- modules/server/src/startProject.js
so my last middleware PR wasn't enough, we need to be able to populate graphql context as well, in order to have access to the user information in the resolver middleware.
I've tested this locally, am 90% sure this gives us what we'll need to properly protect resolvers from KF-arranger
> ✨ need graphql context options as well

- modules/mapping-utils/src/resolveSets.js
- modules/schema/src/Root.js
`refresh` flag as layed out here: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-index
> 🐛 passes refresh to saveSet, defaulting to "WAIT_FOR"

- modules/components/src/DataTable/utils.js
gives the parent repo the opportunity to inject custom columns into the arranger data table
> ✨ support parent-repo configured custom columns

- modules/components/src/Admin/Dashboard.css
- modules/components/src/Admin/Dashboard.js
- modules/components/src/Admin/ProjectsTable.js
- modules/components/src/Admin/Tabs/MatchBoxTab.js
- modules/components/src/Arranger/MatchBox.js
- modules/components/src/utils/parseInputFiles.js
- modules/mapping-utils/src/mappingToMatchBoxState.js
- modules/server/package-lock.json
- modules/server/package.json
- modules/server/src/projects/addType.js
- modules/server/src/projects/export.js
- modules/server/src/projects/getFields.js
- modules/server/src/projects/index.js
- modules/server/src/server.js
- modules/server/src/startProject.js
- modules/server/src/utils/getTypes.js
- modules/server/src/utils/initializeExtendedFields.js
- modules/server/src/utils/replaceBy.js
- package-lock.json
Adds the ability to export (download) an arranger project config, and import (upload) config when adding a type.
Export comes in a tarball, with one subdir per type. Each type includes the `extended`, `aggs-state`, `columns-state`, and `matchbox-state` json config files.
When adding a type you can optionally upload config files, which are stored with the type in the arranger version meta. The spinup flow hasn't changed - extended fields are initialized in `addType`, the other states are initialized on spinup.
Import treats the generated mapping as the source of truth, and just overwrites fields that have a config found in one of the uploaded config files, if they exist.
> ✨import/export arranger config

- modules/mapping-utils/src/resolveAggregations.js
- modules/middleware/src/buildAggregations.js
- modules/middleware/src/buildQuery/index.js
- modules/middleware/test/buildAggregations.test.js
handles this edge case: https://github.com/kids-first/kf-portal-ui/issues/488
The solution was to post process the aggs before feeding into Elasticsearch, by finding aggregation fields that share a direct parent with any query, and drop such queries down to that aggregation as filters. In effect, this creates a new layer of temporary aggregation for the filters for every aggregation field to ensure nothing is missed.
If `aggregationsFilterThemselves` is falsey, the injection will exclude filters that match the aggregation field exactly.
Tried to do it TDD so we got 4 new test cases added. No logical change to existing tests, other than matching up with new function signature.
> 🐛 Aggregations on nested fields are not scoped properly

- integration-tests/import/package.json
- integration-tests/server/package.json
- lerna.json
- modules/components/package.json
- modules/mapping-utils/package.json
- modules/middleware/package.json
- modules/middleware/src/buildAggregations/getNestedSqonFilters.js
- modules/middleware/src/buildAggregations/index.js
- modules/middleware/src/buildAggregations/injectNestedFiltersToAggs.js
- modules/middleware/test/buildAggregations/buildAggregations.test.js
- modules/middleware/test/buildAggregations/getNestedSqonFilters.test.js
- modules/middleware/test/buildAggregations/injectNestedFiltersToAggs.test.js
- modules/schema/package.json
- modules/server/package.json
fixes the break caused by https://github.com/overture-stack/arranger/pull/428
Things done: 
- split out `getNestedSqonFilters` for testing and adds falsey check on `content.field` there
- general file organization (sorry for the big diff...)
- created a `0.4.4-beta` release for testing in beta portal (we'll bump this to 0.4.4 after merging to master)
> 🐛 handles sqon with no fields specified and organizes file structures

- modules/mapping-utils/src/resolveHits.js
- modules/server/src/download/index.js
- modules/server/src/utils/config.js
- modules/server/src/utils/dataToTSV.js
**What was done**
Due to a large amount of data tranformation happening in the hits resolver (`modules/mapping-utils/src/resolveHits.js`), file download is extremely slow. To address this, the following changes were made:
1) A slight modification to the resolveNested function. The original had a very mutation-free approach that creates a new accumulator on every iteration, which implied an iteration over previously accumulated results. Removing this operation significantly improves the performance (consider this benchmark: https://www.measurethat.net/Benchmarks/ShowResult/27779). Only ephemeral mutation is added for this, so all existing tests passed. However, to be extra confident, I would like to get some tests from @cy written to assure accuracy when the copy_to field is involved.
2) …
> ⚡️ hits resolution performance boost

- modules/mapping-utils/src/resolveAggregations.js
- modules/middleware/src/buildAggregations/createFieldAggregation.js
- modules/middleware/src/buildAggregations/index.js
- modules/middleware/test/buildAggregations/createFieldAggregation.test.js
- modules/schema/package.json
Issue identified: 
1) `createAggregation` was using `Array.find` to identify the aggregation type requested, which only picks up the first type. 
Solution: `createAggregation` was stripped out as `createFieldAggregation`, updated to use `Array.reduce` to iterate over each aggregation type and produce the ES aggregation accordingly.
2) Aggregation query arguments were not passed being processed, hence not available to `createNumericAggregation`. 
Solution: as per `graphql-fields`'s doc, `{ processArguments: true }` needed to be passed, and arguments are passed down under `__arguments` in the resulting field object.
Additional issue: `getFields` from `graphql-fields` does not handle graphql alias, preventing resolution of multiple aggregations of the same type on the same field. A …
> fixes histogram query not showing

- integration-tests/import/package.json
- integration-tests/server/package.json
- lerna.json
- modules/admin-ui/package.json
- modules/admin/package.json
- modules/components/package.json
- modules/mapping-utils/package.json
- modules/middleware/package.json
- modules/schema/package.json
- modules/server/package.json
The range filter "clear" link used to reset the values of min and max fields to the original values, but it wasn't working anymore.
It is now fixed and the package was published to v1.0.36.
> v1.0.36 - fix range filter clear link

- server.Dockerfile
mhart/alpine-node image has been updated and the last version seems to be broken.
> Set the base docker image version

- ui.Dockerfile
This afternoon, they have updated the nginx image and a similar error to the one existent with the alpine image appears (I think that alpine is the base image for the Nginx version). Since there aren't more docker recipes, I hope everything should be fixed.
> Add version to nginx image

- Dockerfile
this is neccessary, since in some k8s environment, the disk is readonly. This allows us to define an volitile and writable directory in k8s (emptyDir), and then configure the container render the template to that directory, and nginx to read the config from the directory
> add configurable nginx path to dockerfile

- modules/mapping-utils/src/createConnectionTypeDefs.js
- modules/mapping-utils/src/resolveHits.js
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.x/api-reference.html#_search
Add parameter for `track_total_hits`, defaulted to true
> add track total hits in hit resolver + schema

- modules/server/src/utils/projects.js
This change executes a query, replacing the missing deprecated functionality.
> [644] replace deprecated runQuery method

- Dockerfile
Hardwiring /custom-nginx/ here as a stopgap, while we change the helmcharts to take a config map.
NGINX_CONF_PATH is passed as a `path/filename`, whereas it should just be the `path`, and filename be defined here
> [650] add stopgap hardwired path for env vars

- modules/components/src/DataTable/DataTable.js
- modules/components/stories/table.js
Added more sessionStorage controlled functionality. Row selections in the DataTable will be stored in sessionStorage when changed and read in when the table is constructed. The existing storage methods now have slightly more generic methods to reduce the code repetititition.
Setting sessionStorage to true is sufficient to keep the selections while navigating through the app, but to make the selections persists over page loads, the data table also requires `keepSelectedOnPageChange={true}`. This is an old existing property that afaik wasn't previously doing anything. I kept this as it was just in case it had an existing use I am unaware of, and also since it was working as expected based on the property name.
> DataTable store row selections

- modules/components/src/DataTable/DataTable.js
- modules/components/src/DataTable/TableToolbar/TableToolbar.js
@joneubank realised not all projects want to use the row selection as a filter, so this adds the option to disable that feature.
> add row selection filter for table exporters

- modules/components/src/DataTable/TableToolbar/TableToolbar.js
- modules/components/src/DataTable/TableToolbar/helpers.js
This one should be straightforward:
Custom exporters may want to specify their desired file names.
> add capacity to customise export filenames

- modules/components/src/DataTable/TableToolbar/TableToolbar.js
- modules/components/src/DataTable/TableToolbar/helpers.js
- modules/components/src/DropDown/DropDown.css
- modules/components/src/DropDown/DropDown.js
So users can now render React components, and even text without an exporter.
> Allow alternate "labels" in toolbar dropdown

- modules/components/src/DataTable/TableToolbar/TableToolbar.js
After recent changes to HCMI from https://github.com/nci-hcmi-catalog/portal/pull/915 , it was noted that columns with their `Header` set as a function would render as a blank row in the column select dropdown. This is because the `itemToText` function expects the `Header` to be a string.
With this change, that function will use the optional `displayName` for a column instead (if available).
Commits:
🐛 Add support for non-text column `Header`s in MultiSelectDropdown
* Fixes a bug where column Headers set as functions would render as empty rows in the column selection dropdown
> 🐛 Add support for non-text column `Header`s in MultiSelectDropdown

- modules/components/src/Arranger/Aggregations.js
* Adds a `customFacets` prop to `Aggregations` which takes a list of objects with custom properties for the aggregation with a matching field name
Works similarly to the `customColumns` prop of the Arranger `Table`. Example prop value:
```
[
{
content: {
field: 'field_name',
displayName: 'New Display Name for This Field',
},
},
]
```
> ✨ Add support for customizing Aggregation Facet content (#673)

- modules/server/src/utils/dataToExportFormat.js
Due to custom columns in search table, it is possible to not have a string value in the Header property for a column. In its place, the displayName value is used. This is a common pattern used with the columns object, adding it here to have header string values available for dataStream exports.
> Use displayName instead of Header for data stream if available

- modules/server/src/network/aggregations/index.ts
- modules/server/src/network/index.ts
- modules/server/src/network/typeDefs/aggregations.ts
- modules/server/src/network/typeDefs/networkAggregations.ts
Fixes bucket resolution 
example: 
Server1 buckets: [Cat, Dog]
Server2 buckets: [Cat, Bird]
Output: [Cat, Dog, Bird]
> Fix network agg resolution

- modules/server/src/network/aggregations/index.ts
- modules/server/src/network/httpResponses.ts
- modules/server/src/network/index.ts
- modules/server/src/network/queries/index.ts
- modules/server/src/network/resolvers/aggregations.ts
- modules/server/src/network/resolvers/index.ts
- modules/server/src/network/resolvers/remoteConnections.ts
- modules/server/src/network/resolvers/response.ts
- modules/server/src/network/typeDefs/aggregations.ts
- modules/server/src/network/types.ts
- modules/server/src/network/util.ts
covers feedback from last demo
- batches resolving of aggregations as network node queries return instead of after all queries return
- changes gql response shape (including typedefs and resolver config changes)
- uses Jon's well tested success/failure code for network handling
There are some loose typings (any) to be addressed in future PR
aggregationPipeline mutates objects in order to batch results, comments clearly denote where this happens
open to suggestions for pure functional equivalent
> Response data & batching requests

- modules/server/src/network/gql.ts
- modules/server/src/network/index.ts
- modules/server/src/network/resolvers/aggregations.ts
- modules/server/src/network/resolvers/index.ts
- modules/server/src/network/resolvers/networkNode.ts
- modules/server/src/network/setup/fields.ts
- modules/server/src/network/setup/query.ts
- modules/server/src/network/typeDefs/aggregations.ts
- modules/server/src/network/types/types.ts
- get available aggregations per node on api fetch response
- only send nodes queries with their individually available aggregations
- returns available aggregations with resolver info
> Individual node config query fields

- modules/server/src/app.js
This PR changes the middleware order in the Express app to ensure that Express `json()` and `urlencoded()` are executed before any routing logic. 
This change is required to ensure that Express middlewares controls the maximum request body size, property that is defined in:
```
app.use(urlencoded({ extended: false, limit: '50mb' }));
app.use(json({ limit: '50mb' }));
```
Fixes the issue:
- Getting a Response`413 request entity too large` calling the endpoint `POST http://arranger/download`  with a body larger than 100kb
Please choose only the relevant options and remove the others.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
You do not need to fullfill all …
> Fix Express middleware order

- modules/charts/README.md
- modules/charts/src/components/charts/BarChart/BarChart.tsx
- modules/charts/src/components/charts/BarChart/BarChartView.tsx
- modules/charts/src/hooks/useColorMap.tsx
Moves "handlers" props to top level instead of nested in "theme/config"
Doesn't alter underlying Nivo config resolution
Adds missing file that broke build
> Moves handlers prop to top level

- modules/components/src/aggregations/TermAggs/TermAggs.jsx
Fixes Expanded Facet dropdown text to read 'Less' instead of '0 More'
Fixes item #5 in HCMI Node 24 Feedback:
https://docs.google.com/document/d/1vLtPxRjmP-35LwdTdWdkMEMkfv-ISFG3Z8pDElv9tAQ/edit?usp=sharing
Tested locally:
- I have performed a self review of code
- I have run the application locally and manually tested the feature
- I have checked all updates to correct typos and misspellings
- [] **Formatting**
- Code follows the project style guide
- Autmated code formatters (ie. Prettier) have been run
- Successfully built all packages locally
- Successfully ran all test suites, all unit and integration tests pass
- Unit and integration tests have been added that describe the bug that was fixed or the features that were added
- All new environment variables added to `.env.schema` file …
> Fix: 'Show Less' dropdown display
