overture-stack/arranger

modules/components/public/themeStyles/beagle.css
modules/components/src/Aggs/TermAgg.css
modules/components/src/Aggs/TermAgg.js
modules/components/stories/Aggs.js

Adds a layer above the TermAggs to toggle collapsing, with style

:sparkles: Collapsible TermAggs

---

README.md
modules/components/.storybook/addons.js
modules/components/.storybook/config.js
modules/components/package.json
modules/components/public/themeStyles/beagle.css
modules/components/src/Admin/Dashboard.js
modules/components/src/Aggs/AggsQuery.js
modules/components/src/ThemeSwitcher/index.js
modules/components/stories/Portal.js
modules/components/yarn.lock
package.json

Make specific endpoints for stories / conceopts
- admin server
- dashboard
- portal
- all stories

Distinct servers

---

.gitignore
modules/components/src/Admin/Dashboard.js
modules/components/src/Admin/ProjectsTable.js
modules/components/src/Admin/TypesTable.js
modules/server/src/projects/deleteType.js
modules/server/src/projects/index.js
package.json

for #36 , also fixed an issue where following a project link wasn't setting it as the activeProject

:sparkles: added delete type

---

modules/components/public/themeStyles/beagle/beagle.css
modules/components/src/DataTable/TableToolbar/TableToolbar.js
modules/components/src/DataTable/TableToolbar/Toolbar.css
modules/components/src/DropDown/DropDown.css
modules/components/src/DropDown/DropDown.js
modules/components/src/Input/Input.css
modules/components/src/Input/Input.js
modules/components/src/Input/index.js

Just styling the table toolbar

💄Feat/toolbar beagle

---

modules/components/package.json
modules/components/src/Admin/Dashboard.js
modules/components/src/DataTable/TableToolbar/TableToolbar.js

fontawesome breaks when imported for some reason.

replace fontawesome with react-icons

---

package.json

only bootstraps required packages

✨ update netlify command so it's faster

---

modules/components/src/AdvancedFacetView/Facets/NumericAggregation.js
modules/components/src/AdvancedFacetView/Facets/TermAggregation.js
modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
modules/components/src/AdvancedFacetView/index.js
modules/components/src/Arranger/index.js
modules/components/stories/AdvancedFacetView.js

This is just to temporarily handle null case for the demo. We need to look into the underlying problem later

🐛handles null aggregation in advanced facet view for demo

---

modules/components/public/themeStyles/beagle/beagle.css

💄 update styles

---

modules/components/src/Arranger/DetectNewVersion.js

https://github.com/facebook/react/issues/3725#issuecomment-355965170

🐛 defaultProps should be static

---

modules/components/package.json
modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
modules/components/stories/AdvancedFacetView.js

This only addresses updating the advanced facet view (afv), the same thing needs to be done in the actual portal for Kids First as well

✨ updates the aggregations given the new sqon

---

.dockerignore
.gitignore
integration-tests/import/.babelrc
integration-tests/import/__mocks__/styleMock.js
integration-tests/import/package.json
integration-tests/import/test.js
lerna.json
modules/components/package.json
modules/components/src/Admin/Dashboard.js
modules/components/src/Admin/ProjectsTable.js
modules/components/src/Admin/TypesTable.js
modules/components/src/Arranger/index.js
modules/components/src/index.js
modules/components/stories/Dashboard.js
modules/middleware/package.json

I'm kind of happy how this experiment turned out? I wanted to change the way arranger/components were being exported and I knew it was going to break stuff. 
this PR in its current state doesn't cover that entirely but I think this could be used as a decent model for integration tests moving forward.

fixing export locations / test successful importing

---

modules/components/package.json
modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
modules/components/src/Aggs/AggsQuery.js
modules/components/stories/Portal.js

Needs to remove this dependency as integration into KF portal fails to minify during build

🔥🐛removes stringify-object dependency

---

modules/middleware/src/aggregations.js
modules/middleware/test/global_aggs.test.js
modules/server/src/projects/index.js
modules/server/src/utils/config.js

1) add ES_LOG variable to change server terminal output (thanks @jgnieuwhof )
2) fix "aggregations_should_filter_themselves" to handle agg panel values

🐛 transcription fix for global_aggs

---

modules/components/package-lock.json
modules/components/package.json
modules/components/src/AdvancedFacetView/FacetView.js
modules/components/src/AdvancedFacetView/FacetViewNode.js
modules/components/src/AdvancedFacetView/Facets/TermAggregation.js
modules/components/src/AdvancedFacetView/Facets/index.js
modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
modules/components/src/AdvancedFacetView/SearchBox.js
modules/components/src/AdvancedFacetView/index.js
modules/components/src/Aggs/TermAgg.js
modules/components/src/State.js

✨ Adds ability to search values in the afv

---

modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js

- refactors to allow field types to exclude to be passed in
- includes 'date' type in default

💩 refactors to allow field types to exclude to be passed in

---

modules/server/src/index.js
modules/server/src/projects/getProjects.js
modules/server/src/projects/teardown.js
modules/server/src/startProject.js
modules/server/src/utils/projects.js

This fixes the issue of not being to have multiple versions running concurrently. it also fixes an issue that was preventing active projects from starting up on server boot

🐛 handle startup promise rejection

---

modules/middleware/src/aggregations.js

🐛 use correct path variable

---

modules/server/src/startProject.js

This will append new columns to the existing columns

✨ if existing columns and new columns merge them

---

modules/components/src/Aggs/AggsWrapper.js
modules/components/src/Aggs/BooleanAgg.css
modules/components/src/Aggs/BooleanAgg.js
modules/components/src/Aggs/RangeAgg.js
modules/components/src/Aggs/TermAgg.js
modules/components/src/Aggs/index.js
modules/components/src/SQONView/utils.js
modules/components/stories/Aggs.js

Boolean aggs

---

modules/middleware/test/buildAggregations.test.js
modules/middleware/test/buildQuery/buildQuery.test.js
modules/middleware/test/buildQuery/buildQueryNested.test.js
modules/middleware/test/buildQuery/buildQuerySetId.test.js
modules/middleware/test/buildQuery/buildQueryWildcard.test.js
modules/middleware/test/flattenAggregations.test.js

making a separate pull request so the diff isn't cluttered.

✨ middleware tests

---

modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
modules/components/stories/AdvancedFacetView.js

also adds a more meaningful test sqon for the story

feeds sqon into initial aggregation fetch

---

modules/server/src/download/index.js
modules/server/src/utils/getAllData.js

It was taking too long until the first byte, this makes it more responsive.

✨lower chunk size

---

modules/middleware/src/buildAggregations.js
modules/middleware/src/flattenAggregations.js
modules/middleware/test/buildAggregations.test.js
modules/middleware/test/flattenAggregations.test.js

✨ add missing bucket

---

modules/middleware/test/buildAggregations.test.js

✅ merge mishap, test grooming was missed

---

modules/components/src/DataTable/ColumnsState.js

required for https://github.com/kids-first/kf-portal-ui/pull/218

do not filter extended by active fields

---

integration-tests/server/test/index.test.js
integration-tests/server/test/saveSet.js
modules/mapping-utils/package-lock.json
modules/mapping-utils/package.json
modules/mapping-utils/src/index.js
modules/mapping-utils/src/resolveSets.js
modules/schema/package-lock.json
modules/schema/package.json
modules/schema/src/Root.js
modules/schema/src/Sets.js
modules/server/package-lock.json
modules/server/src/startProject.js
package-lock.json

This adds an endpoint to save sets.
Some TODOs:
- set fetching
- set searching
- configurable set ID fetching via aggs rather than scroll ES api

 ✨ add ability to save sets

---

modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
modules/components/src/Aggs/AggsQuery.js
modules/components/src/Aggs/AggsState.js
modules/components/src/Arranger/Aggregations.js
modules/components/src/Arranger/Arranger.js
modules/components/src/Arranger/GetProjects.js
modules/components/src/Arranger/Table.js
modules/components/src/DataTable/ColumnsState.js
modules/components/src/Query.js

Allows components to be fed a custom fetcher for data fetching. This allows consumers to handle use-case specific error handling

✨ Make components that fetch data accept custom fetcher

---

modules/components/public/themeStyles/beagle/beagle.css
modules/components/src/AdvancedFacetView/AdvancedFacetView.css
modules/components/src/AdvancedFacetView/FacetView.js
modules/components/src/Aggs/TermAgg.js
modules/components/src/NestedTreeView/NestedTreeView.js
modules/components/src/NestedTreeView/ReactTreeView.js

style ref: https://zpl.io/bP4BdYD

💄 More accurate afv style according to design

---

modules/mapping-utils/src/mappingToFields.js
modules/mapping-utils/src/mappingToNestedTypes.js
modules/schema/src/Root.js

i am dumb, `|| true` will never be false lalalala, fixup

:bug: fix resolve sets no agg/col/matchBoxState

---

modules/components/src/Arranger/CurrentSQON.js
modules/components/src/Arranger/QuickSearch/QuickSearch.js

Can pass in a function to components that display sqon values, to translate / filter the value text. used in KF for set names.

✨ can pass in a function to rename sqon values

---

modules/components/package-lock.json
modules/components/package.json
modules/components/src/utils/download.js
modules/components/src/utils/initSocket.js
modules/server/package-lock.json
modules/server/src/download/index.js
modules/server/src/startProject.js

cookies don't work cross-origin, sockets do. this fix has the added benefit of resolving the download once the file is actually done streaming to the user, which is kinda neat.

🐛 fix - download progress

---

modules/components/public/themeStyles/beagle/beagle.css
modules/components/src/Admin/Dashboard.js
modules/components/src/Aggs/BooleanAgg.js
modules/components/src/Arranger/CurrentSQON.js
modules/components/src/DataTable/ColumnsState.js
modules/components/src/DataTable/Table/Table.js
modules/components/src/DataTable/columnTypes.js
modules/components/src/DataTable/utils.js
modules/components/src/SQONView/index.js
modules/mapping-utils/src/extendFields.js
modules/server/src/utils/dataToTSV.js

https://github.com/kids-first/kf-portal-ui/issues/267
adds the ability to configure display values for boolean fields.

✨ boolean display values

---

modules/components/src/Admin/Dashboard.js

🐛 dashboard fix

---

modules/components/src/Aggs/aggComponentsMap.js
modules/mapping-utils/src/mappingToScalarFields.js

and display RangeAgg for type int (age of dig. on hcmi's test es)

:bug: sets: resolve sqon field

---

modules/components/public/themeStyles/beagle/beagle.css
modules/components/src/AdvancedFacetView/FacetView.js
modules/components/src/Aggs/AggregationCard.css
modules/components/src/Aggs/AggsWrapper.js
modules/components/src/Aggs/BooleanAgg.js
modules/components/src/Aggs/TermAgg.js
modules/components/src/Input/Input.js

adds search terms in the term agg facet, as well as term agg sticky header

✨ add term agg filtering

---

modules/components/src/DataTable/DataTable.js

🐛 onSortedChange is an optional prop

---

modules/components/package-lock.json
modules/mapping-utils/src/extendMapping.js
modules/mapping-utils/src/index.js
modules/server/src/projects/addType.js
modules/server/src/projects/getFields.js
modules/server/src/startProject.js

once extended mapping is created we need to ensure that new extended fields are accessible / configurable

🐛 fix extended mapping should include newly added extended fields

---

modules/components/src/DataTable/DataTable.js

#360 prevented config.defaultSorted being null, so now need to move onSortedChange call to constructor

move config.default onSortChange to constructor

---

modules/components/package-lock.json
modules/components/src/AdvancedFacetView/FacetView.js
modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
modules/components/src/AdvancedFacetView/index.js
modules/components/src/AdvancedFacetView/utils.js
modules/components/src/NestedTreeView/NestedTreeView.js
modules/components/src/NestedTreeView/ReactTreeView.js

nests non-nested fields in the advanced facet view under a virtual parent named after the index itself

✨ nest root afv fields under a root type

---

modules/components/package-lock.json
modules/components/package.json
modules/components/public/themeStyles/beagle/beagle.css
modules/components/src/Aggs/DatesAgg.js

ditching react-dates, this one seems to work well

🐛 new date picker that can handle year changes

---

modules/components/public/themeStyles/beagle/beagle.css
modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
modules/components/src/AdvancedFacetView/index.js
modules/components/src/Aggs/AggsQuery.js
modules/components/src/Aggs/AggsState.js
modules/components/src/Arranger/index.js
modules/components/src/Stats/CombinedStatsQuery.js
modules/components/src/Stats/Stats.js
modules/components/src/Stats/index.js

I think this is ready to go. Introduced some helper components to display / query stats.
It's config'd via a stats prop, to be subbed in by arranger admin config at some point (maybe when we get to plugin land).

✨ feat/stats component

---

modules/components/src/Arranger/Table.js

Propagate the debounced filter change event and it's search input value up to the Table component to allow for event hooks

Add onFilterChange to prop to Table component

---

modules/components/src/NestedTreeView/NestedTreeView.js

it was checking against just local id...

🐛fixes the treeview selected path rendering

---

modules/components/src/DataTable/Table/CustomPagination.js

This just rounds the page index down to an integer

🐛fixes the pagination page index

---

modules/components/src/Admin/Tabs/Aggregations/TableTab.js
modules/server/package-lock.json
modules/server/package.json
package-lock.json

table tab wasn't loading for me anymore. This fixes.

:bug: null in TableTab causing it to crash

---

modules/components/src/AdvancedFacetView/index.js
modules/components/src/Arranger/CurrentSQON.js
modules/components/src/TextHighlight/index.js
modules/components/src/utils/strToReg.js
modules/components/stories/AdvancedFacetView.js

A couple things here:
- fixed the searching behaviour. instead of ignoring invalid chars we'll escape them & return no results
- AFV now uses CurrentSQON, since CurrentSQON has some helper functionality

🐛 advanced facet view searching

---

modules/components/package-lock.json
modules/components/public/themeStyles/beagle/beagle.css
modules/components/src/Arranger/MatchBox.js

this is needed for https://github.com/kids-first/kf-portal-ui/pull/386

makes match box vertically responsive

---

modules/mapping-utils/src/resolveHits.js
modules/middleware/.babelrc
modules/middleware/package-lock.json
modules/middleware/package.json
modules/middleware/src/constants.js
modules/middleware/src/index.js
modules/server/package-lock.json
package-lock.json

explanation here https://github.com/elastic/elasticsearch-js/issues/662
this is a stopgap until ES-JS sol'n exists

🐛 JS can't handle ES's max long special val, give them a str ver

---

modules/components/package-lock.json
modules/mapping-utils/src/hackyTemporaryEsSetResolution.js
modules/mapping-utils/src/resolveAggregations.js
modules/mapping-utils/src/resolveSets.js
modules/middleware/src/buildQuery/index.js
modules/middleware/src/constants.js
modules/middleware/test/buildQuery/buildQuerySetId.test.js
modules/schema/src/index.js
modules/server/src/startProject.js

basically just resolving sets into actual ids in sqon before feeding it in to build query

🐛 Bug/sets and sqon

---

modules/components/package-lock.json
modules/components/src/Aggs/BooleanAgg.js
modules/components/src/Aggs/RangeAgg.js
modules/components/src/Aggs/TermAgg.js
modules/components/src/Arranger/MatchBox.js
modules/components/src/Stats/Stats.js
modules/components/src/utils/formatNumber.js
modules/components/src/utils/translateSQONValue.js

added a helper function to format numbers

💄 numbers should be formatted properly

---

modules/components/public/themeStyles/beagle/beagle.css
modules/components/stories/Portal.js

💄 move layout agg bar width to KF portal

---

modules/components/package-lock.json
modules/components/src/Arranger/MatchBox.js

🐛 fix poorly done merge that broke match box

---

modules/components/src/DataTable/DataTable.js
modules/components/src/DataTable/TableToolbar/TableToolbar.js
modules/components/src/TextFilter/TextFilter.js
modules/components/stories/table.js

✨ adds filterInputPlaceholder prop

---

modules/components/src/AdvancedFacetView/index.js
modules/components/src/Aggs/TermAgg.js
modules/components/src/Arranger/QuickSearch/QuickSearch.js
modules/components/src/Arranger/Table.js
modules/components/src/DataTable/DataTable.js
modules/components/src/DataTable/TableToolbar/TableToolbar.js
modules/components/src/TextFilter/TextFilter.js

required for https://github.com/kids-first/kf-portal-ui/pull/451

✨ components that use inputs now receive a custom input component 

---

modules/components/src/DataTable/TableToolbar/TableToolbar.js
modules/components/stories/table.js

Possibility to add custom "content" within a TableToolbar component

#1043 Action Panel Removal and Table Select All

---

modules/components/src/Arranger/Table.js
modules/components/src/DataTable/DataTable.js

Action Panel Removal and Table Select All #1043

---

modules/components/src/AdvancedSqonBuilder/filterComponents/BooleanFilter.js
modules/components/src/AdvancedSqonBuilder/filterComponents/index.js
modules/components/src/ToggleButton/ToggleButton.js
modules/components/stories/AdvancedSqonBuilder/ProjectsProvider.js
modules/components/stories/AdvancedSqonBuilder/index.js
modules/components/stories/AdvancedSqonBuilder/mocks.js

@hlminh2000 I'd like you opinion, just to be sure I'm on track.
@nyanofthemoon fyi

✨ feature/1118 - BooleanFilterUI

---

modules/components/stories/Portal.js
modules/server/src/startProject.js

- uncomment intializeStates in the server side to allow using in storybook
- remove a non existing component from Portal story

fixes: issues running arranger from storybook

---

modules/components/src/AdvancedSqonBuilder/filterComponents/RangeFilter.js

Fixes both https://github.com/kids-first/kf-portal-ui/issues/1464 and https://github.com/kids-first/kf-portal-ui/issues/1462

fix/1464 + fix/1462 convert units only when submitted, display d -> day

---

modules/components/src/AdvancedSqonBuilder/filterComponents/TermFilter.js

https://github.com/kids-first/kf-portal-ui/issues/1551

select all in TermFilter should only select filtered results

---

modules/server/README.md
modules/server/package-lock.json
modules/server/src/startProject.js

Exported the functions used to create a project schema, so the executable schema can be used else where
List of chagnes:
- exports functions
- update package-lock

export functions to create schema without server

---

integration-tests/server/test/manageSets.js
integration-tests/server/test/readAggregation.js
modules/mapping-utils/src/mappingToAggsType.js
modules/middleware/src/buildAggregations/createFieldAggregation.js
modules/middleware/src/constants.js
modules/middleware/src/flattenAggregations.js
modules/middleware/test/flattenAggregations.test.js
modules/schema/src/Aggregations.js

Adds `bucket_count` field in Aggregations to calculate number of buckets when resolving agg query.

⚡️ 503 - calculate bucket count in aggs

---

.dockerignore
.gitignore
Makefile
README.md
docker-compose.yml
docker/elasticsearch/documents/43a4a09d-674f-515b-bb88-1468f52f71c1.json
docker/elasticsearch/documents/45138fc7-3242-564e-a201-6a76db11d8bc.json
docker/elasticsearch/documents/481c26e9-82b2-5cef-adb6-03787d09002b.json
docker/elasticsearch/documents/521dab2e-33c8-5181-bd26-015fb3d61d74.json
docker/elasticsearch/documents/5b3f3faf-ee41-5cab-bce9-1a739adfde34.json
docker/elasticsearch/documents/7b81aa18-f0d5-507a-b713-15ff5f7f59e5.json
docker/elasticsearch/documents/ca5ef4e2-f4b2-5fea-bc7a-fb947b37216c.json
docker/elasticsearch/documents/eb3e59e7-e313-5bca-b488-874d1e6d93cd.json
docker/elasticsearch/index_config.json
docker/elasticsearch/load-es-data.sh
modules/admin/src/index.ts
modules/admin/src/services/elasticsearch/index.ts
modules/admin/src/types.ts
modules/server/src/app.js
modules/server/src/projects/index.js
modules/server/src/server.js
modules/server/src/utils/config.js
scripts/retry-command.sh

Related to #618 
added ES_USER and ES_PASS as OPTIONAL env variable. If both ES_USER and ES_PASS are not defined, then will work as it did before. If ES_USER is defined and ES_PASS is not, will log an error. If both are defined, then will use the username and password for the elasticsearch client
Also added test data (from genomic_data_playground) for the ES index.

Rtisma es passwd

---

Jenkinsfile

Adds commit ref to image versions to be deployed by Helm/K8s

allow deploying to staging without tagging

---

Makefile
README.md

Adds additional details on how to setup and run the project, hopefully in a friendlier manner from a newcomer perspective.
Closes #657.

[657] improve setup instructions

---

modules/components/src/Arranger/Arranger.js
modules/components/src/DataTable/DataTable.js
modules/components/src/DataTable/TableToolbar/TableToolbar.js

Send the Ids in selectedTableRows as part of the download sqon.
Closes #661.

[661] enable row selection filter for downloads

---

modules/components/src/Arranger/CurrentSQON.js

Try plugging it in, before turning it on?

add missing props 'api' being passed to the sqons

---

Jenkinsfile

Added typo fix

---

Jenkinsfile

- Jenkinsfile - fixed ghcr auth problem.

Updated Jenkinsfile - ghcr auth fix

---

modules/components/src/DataTable/DataTable.js
modules/components/src/DataTable/TableToolbar/TableToolbar.js
modules/components/src/DataTable/TableToolbar/Toolbar.css

- Customizable property name for selected row filter
- No longer combines selected rows and current SQON. Use selected rows filter only.

DataTable Selected Rows Improvements

---

modules/components/src/Arranger/CurrentSQON.js

Logic behooves being logical 🤡

fix sqon display conditional logic for date values

---

modules/server/src/startProject.js

Fixes https://github.com/overture-stack/arranger/issues/642

fix:#642 fix missing request response and connection in context function

---

modules/server/src/middleware/__tests__/buildAggregations/createFieldAggregation.test.js
modules/server/src/middleware/buildAggregations/createFieldAggregation.js
modules/server/src/middleware/buildAggregations/index.js
modules/server/src/middleware/buildQuery/index.js

includes changes discussed in #744, ported to the Arranger 3.0 structure

resolve bug in nested aggregations (#744)

---

modules/middleware/src/buildQuery/index.js

Related issue: https://github.com/overture-stack/arranger/issues/809

fix: 809 - missing with not operator

---

modules/components/src/DropDown/MultiSelectDropDown.js
modules/components/src/Table/ColumnsSelectButton/ColumnsSelectButton.tsx
modules/components/src/Table/ColumnsSelectButton/types.ts

Adding filter to Column Select Dropdown.
Enabled by default.

filter multi select dropdown

---

README.md
docs/setup.md

As referenced here: https://github.com/overture-stack/prelude/pull/29

Prelude update

---

modules/charts/src/components/Provider/Provider.tsx
modules/charts/src/components/Provider/hooks/useCharts.tsx
modules/charts/src/gql/index.ts
modules/charts/src/hooks/useNetworkQuery.tsx
modules/charts/src/query/generateCharts.tsx

change back to using frontend gql query generation instead of server side query config

change back to dynamic frontend gql query generation

---

modules/charts/src/components/Chart.tsx
modules/charts/src/components/Provider/Provider.tsx
modules/charts/src/components/charts/Barchart/Barchart.tsx
modules/charts/src/hooks/useRegisterChart.tsx

allow multi field registration for diferent chart types
eg. BarChart is one fieldName , Sunburst is two

allow multi field registration

---

modules/charts/package.json
modules/charts/vite.config.ts

- remove jsx from vite externals config, clashes with consumer project when installed from npm

Feature/charts logging (#972)

---

modules/charts/package.json
modules/charts/src/components/charts/Sunburst/View.tsx
modules/charts/src/components/charts/Sunburst/dataTransform.ts
modules/charts/src/components/charts/Tooltip.tsx

Rc/arranger charts 0.0.1 beta.10

---

modules/components/src/Table/HeaderRow/HeaderRow.tsx
modules/components/src/Table/MaxRowsSelector/MaxRowsSelector.tsx
modules/components/src/Table/PageSelector/PageSelector.tsx
modules/components/src/Table/helpers/columns.tsx

Fixes accessibility issues found in HCMI using Axe DevTools
- [(1118)](https://github.com/nci-hcmi-catalog/portal/issues/1118)
- Adds aria-labels for table checkboxes, column resizer, and max rows selector
- Moves PageSelector role=navigation (previous usage caused an Axe error)
- I have performed a self review of code
- I have run the application locally and manually tested the feature
- I have checked all updates to correct typos and misspellings
- Code follows the project style guide
- Autmated code formatters (ie. Prettier) have been run
- Successfully built all packages locally
- Successfully ran all test suites, all unit and integration tests pass
- Unit and integration tests have been added that describe the bug that was fixed or the features that were added
- All new environment …

#1118 ♿ HCMI Accessibility Fixes
